# Author: Erick Roberto Rodriguez Rodriguez
# Email: erodriguez@tekium.mx, erickrr.tbd93@gmail.com
# GitHub: https://github.com/erickrr-bd/Logstash-configurations
# Logstash configuration for Deep Security Agent v20.0.926 - May 2026

input {
    tcp/udp {
        port => "port"
        codec => cef
    }
}

output {

}