# Author: Erick Roberto Rodriguez Rodriguez
# Email: erodriguez@tekium.mx, erickrr.tbd93@gmail.com
# GitHub: https://github.com/erickrr-bd/Logstash-configurations
# Logstash's configuration for GitHub Enterprise v1.1 - November 2025

input {

}

filter {
        if [message] =~ /github_audit/{
                grok{
                        match => {
                                "message" => "<%{INT}>%{SYSLOGTIMESTAMP:timestamp} %{HOSTNAME:hostname} %{DATA:program}(?:\[%{INT:pid}\])?:\s%{GREEDYDATA:aux_json}"
                        }
                }
                json{
                        source => "aux_json"
                        target => "format_json"
                }
                if [format_json][repo_config]{
                        json{
                                source => "[format_json][repo_config]"
                                target => "[format_json][repo_config_json]"
                        }
                }
        }
        else if [message] =~ /github_access/{
                grok{
                        match => {
                                "message" => "<%{INT}>%{MONTH} %{MONTHDAY} %{TIME} %{HOSTNAME:hostname} %{WORD:program}: - %{USERNAME:username} \[%{DATA:date}\] %{QUOTEDSTRING:request} %{INT:response_code} %{INT:response_size_bytes} %{QUOTEDSTRING:referer} %{QUOTEDSTRING:user_agent_raw} %{QUOTEDSTRING:src_ip} %{NUMBER:request_time} %{NUMBER:upstream_response_time}"
                        }
                }
                grok{
                        match => {
                                "request" => "\"%{WORD:http_method} %{DATA:request_path}\""
                        }
                }
        }
        mutate{
                remove_field => ["message", "aux_json", "[format_json][repo_config]"]
        }
}

output {

}