# Author: Erick Roberto Rodriguez Rodriguez
# Email: erodriguez@tekium.mx, erickrr.tbd93@gmail.com
# GitHub: https://github.com/erickrr-bd/Logstash-configurations
# Logstash configuration for NSX v1.0 - May 2026

input {

}

filter {
        if "FIREWALL-PKTLOG" in [message]{
                grok{
                        match => {
                                "message" => "<%{POSINT:syslog_pri}>%{NONNEGINT:syslog_version} %{TIMESTAMP_ISO8601:timestamp} %{HOSTNAME:esxi_host} %{NOTSPACE:component} %{NOTSPACE:process_id} - - %{NOTSPACE:log_id} %{WORD:network_stack} match %{WORD:action} %{INT:rule_id} %{WORD:direction} %{INT:packet_length} %{WORD:protocol} %{IP:src_ip}/%{INT:src_port}->%{IP:dst_ip}/%{INT:dst_port}"
                        }
                }
        }
        else if "audispd" in [message]{
                grok{
                        match => {
                                "message" => "<%{POSINT:syslog_pri}>%{NONNEGINT:syslog_version} %{TIMESTAMP_ISO8601:timestamp} %{HOSTNAME:manager_node} %{WORD:component} - - - - %{GREEDYDATA:aux_msg}"
                        }
                }
                kv{
                        source => "aux_msg"
                        field_split_pattern => " "
                        value_split => "="
                }
                if "audit(" not in [msg]{
                        kv{
                                source => "msg"
                                field_split_pattern => " "
                                value_split => "="
                        }
                }
        }
        mutate{
                remove_field => ["message", "aux_msg"]
        }
}

output {

}