# Author: Erick Roberto Rodriguez Rodriguez
# Email: erodriguez@tekium.mx, erickrr.tbd93@gmail.com
# GitHub: https://github.com/erickrr-bd/Logstash-configurations
# Logstash configuration for Trend Vision One v1.0.0 - April 2026

input {

}

filter {
        grok {
                match => { "message" => "<%{POSINT}>(?<date>%{MONTH} +%{MONTHDAY} %{YEAR} %{TIME}) %{IP:src_host} CEF:%{INT:cef_version}\|%{DATA:vendor}\|%{DATA:product}\|%{DATA:version}\|%{DATA:signature_id}\|%{DATA:name}\|%{DATA:severity}\|%{WORD}\=(?<rt>%{MONTH} +%{MONTHDAY} %{YEAR} %{TIME}) %{GREEDYDATA:aux_msg}" }
        }
        mutate{
                gsub => [
                        "aux_msg", "=\s+(?=[a-zA-Z0-9]+=)", "=null ",
                        "aux_msg", "\\=", "="
                ]
        }
        grok {
                match => { "aux_msg" => "msg=(?<msg_raw>\{.*?\}) (?=[a-zA-Z0-9]+=)" }
                add_field => { "msg_extracted"  => "true"}
        }
        if [msg_extracted] {
                mutate {
                        gsub => ["aux_msg", "msg=\{.*?\} ", ""]
                }
        }
        kv {
                source => "aux_msg"
                field_split_pattern => "\s+(?=[a-zA-Z0-9]+(=|:))"
                value_split => "="
                trim_value => " "
        }
        if [msg_raw] {
                mutate {
                        gsub => ["msg_raw", "'", '"']
                }
                json {
                        source => "msg_raw"
                        target => "msg_json"
                        skip_on_invalid_json => true
                }
        }
        mutate {
                remove_field => ["msg_raw", "message", "aux_msg", "tags"]
        }
}

output {

}